openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
paths:
  /tasks/{taskId}:
    get:
      summary: Get a task's details
      operationId: getTask
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
          description: The ID of the task
      responses:
        '200':
          description: Execution report of the task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionReport'
        '400':
          description: Invalid task ID
        '404':
          description: Task ID not found

    delete:
      summary: Cancel a task
      operationId: cancelTask
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
          description: The ID of the task
      responses:
        '204':
          description: Task has been cancelled
        '400':
          description: Invalid task ID

  /tasks/{taskId}/await:
    get:
      summary: Await the completion of a task
      operationId: awaitTaskCompletion
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
          description: The ID of the task
        - in: query
          name: timeout
          schema:
            type: string
          description: The timeout duration in the format Nunit (e.g., 30s, 5m, 7d, 1y)
      responses:
        '200':
          description: Execution report of the task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionReport'
        '400':
          description: Invalid task ID or invalid timeout
        '404':
          description: Task ID not found
        '408':
          description: Timeout reached

  /tasks:
    get:
      summary: List tasks
      operationId: listTasks
      parameters:
        - in: query
          name: status
          schema:
            type: string
          description: The status of the tasks (waiting, inProgress, canceledRequested, completed, canceled, failed)
        - in: query
          name: type
          schema:
            type: string
          description: The type of the tasks
        - in: query
          name: submittedBefore
          schema:
            type: string
            format: date-time
          description: Return tasks submitted before this date
        - in: query
          name: submittedAfter
          schema:
            type: string
            format: date-time
          description: Return tasks submitted after this date
        - in: query
          name: startedBefore
          schema:
            type: string
            format: date-time
          description: Return tasks started before this date
        - in: query
          name: startedAfter
          schema:
            type: string
            format: date-time
          description: Return tasks started after this date
        - in: query
          name: completedBefore
          schema:
            type: string
            format: date-time
          description: Return tasks completed before this date
        - in: query
          name: completedAfter
          schema:
            type: string
            format: date-time
          description: Return tasks completed after this date
        - in: query
          name: failedBefore
          schema:
            type: string
            format: date-time
          description: Return tasks failed before this date
        - in: query
          name: failedAfter
          schema:
            type: string
            format: date-time
          description: Return tasks failed after this date
        - in: query
          name: offset
          schema:
            type: integer
            format: int32
          description: Number of tasks to skip in the response
        - in: query
          name: limit
          schema:
            type: integer
            format: int32
          description: Maximum number of tasks to return in one call
      responses:
        '200':
          description: List of corresponding tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExecutionReport'
        '400':
          description: Invalid status value

components:
  schemas:
    ExecutionReport:
      type: object
      properties:
        submitDate:
          type: string
          format: date-time
          description: The submission date of the task
        startedDate:
          type: string
          format: date-time
          description: The start date of the task execution
        completedDate:
          type: string
          format: date-time
          description: The completion date of the task execution
        cancelledDate:
          type: string
          format: date-time
          nullable: true
          description: The cancellation date of the task (null if not cancelled)
        failedDate:
          type: string
          format: date-time
          nullable: true
          description: The failure date of the task (null if not failed)
        taskId:
          type: string
          description: The ID of the task
        additionalInformation:
          type: object
          description: Additional information about the task
        status:
          type: string
          enum: [waiting, inProgress, cancelled, completed, failed]
          description: The status of the task
        type:
          type: string
          description: The type of the task
