openapi: 3.0.0
info:
  title: Mailbox Management API
  version: 1.0.0
paths:
  /users/{username}/mailboxes/{mailboxNameToBeCreated}:
    put:
      summary: Create a mailbox
      operationId: createMailbox
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
        - in: path
          name: mailboxNameToBeCreated
          required: true
          schema:
            type: string
      responses:
        '204':
          description: The mailbox now exists on the server
        '400':
          description: Invalid mailbox name
        '404':
          description: The user name does not exist

  /users/{username}/mailboxes/INBOX.work:
    delete:
      summary: Delete a mailbox and its children
      operationId: deleteMailbox
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
        - in: path
          name: mailboxNameToBeDeleted
          required: true
          schema:
            type: string
      responses:
        '204':
          description: The mailbox now does not exist on the server
        '400':
          description: Invalid mailbox name
        '404':
          description: The user name does not exist

  /users/{username}/mailboxes/{mailboxNameToBeTested}:
    get:
      summary: Test existence of a mailbox
      operationId: existsMailbox
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
        - in: path
          name: mailboxNameToBeTested
          required: true
          schema:
            type: string
      responses:
        '204':
          description: The mailbox exists
        '400':
          description: Invalid mailbox name
        '404':
          description: The user name does not exist, or the mailbox does not exist

  /users/{username}/mailboxes:
    get:
      summary: List user mailboxes
      operationId: listMailboxes
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The mailboxes list was successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    mailboxName:
                      type: string
        '404':
          description: The user name does not exist

    delete:
      summary: Delete user mailboxes
      operationId: deleteMailboxes
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
      responses:
        '204':
          description: The user does not have mailboxes anymore
        '404':
          description: The user name does not exist

  /users/{username}/mailboxes?action=export:
    post:
      summary: Export user mailboxes
      operationId: exportMailboxes
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Success. Corresponding task ID is returned
        '404':
          description: The user name does not exist

  /users/{username}/mailboxes?task=reIndex:
    post:
      summary: Reindex a user's mails
      operationId: reindexEmails
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
        - in: query
          name: messagesPerSecond
          schema:
            type: integer
            minimum: 1
            default: 50
        - in: query
          name: mode
          schema:
            type: string
            enum: [rebuildAll, rebuildAllNoCleanup, fixOutdated]
            default: rebuildAll
      responses:
        '201':
          description: Success. Corresponding task ID is returned
        '400':
          description: Error in the request. Details can be found in the reported error
        '404':
          description: User not found

  /users/{username}/mailboxes/{mailboxName}/messageCount:
    get:
      summary: Count emails in a mailbox
      operationId: countEmails
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
        - in: path
          name: mailboxName
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The number of emails in the given mailbox
        '400':
          description: Invalid mailbox name
        '404':
          description: Invalid get on user mailboxes. The username or mailboxName does not exist

  /users/{username}/mailboxes/{mailboxName}/unseenMessageCount:
    get:
      summary: Count unseen emails in a mailbox
      operationId: countUnseenEmails
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
        - in: path
          name: mailboxName
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The number of unseen emails in the given mailbox
        '400':
          description: Invalid mailbox name
        '404':
          description: Invalid get on user mailboxes. The username or mailboxName does not exist

  /users/{username}/mailboxes/{mailboxName}/messages:
    delete:
      summary: Clear mailbox content
      operationId: clearMailbox
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
        - in: path
          name: mailboxName
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Success. Corresponding task ID is returned
        '400':
          description: Invalid mailbox name
        '404':
          description: Invalid get on user mailboxes. The username or mailboxName does not exist

  /users/{username}/mailboxes?task=subscribeAll:
    post:
      summary: Subscribe a user to all of their mailboxes
      operationId: subscribeAllMailboxes
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Success. Corresponding task ID is returned
        '404':
          description: No such user

  /users/{username}/mailboxes?task=recomputeFastViewProjectionItems:
    post:
      summary: Recompute User JMAP fast message view projection
      operationId: recomputeMessageViewProjection
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
        - in: query
          name: messagesPerSecond
          schema:
            type: integer
            minimum: 1
            default: 10
      responses:
        '201':
          description: Success. Corresponding task ID is returned
        '400':
          description: Error in the request. Details can be found in the reported error
        '404':
          description: User not found

  /mailboxes?task=populateFilteringProjection:
    post:
      summary: Recompute Cassandra filtering projection
      operationId: recomputeCassandraFilteringProjection
      responses:
        '201':
          description: Success. Corresponding task ID is returned
        '400':
          description: Error in the request. Details can be found in the reported error
